# Generated by Django 6.1.1 on 2026-10-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], max_length=20, null=True, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Лог статуса бронирования',
                'verbose_name_plural': 'Логи статусов бронирования',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('device_type', models.CharField(blank=True, choices=[('PC', 'ПК'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X/S')], help_text='Если ждет любую консоль/ПК определённого типа', max_length=10, null=True, verbose_name='Тип устройства')),
                ('desired_start', models.DateTimeField(verbose_name='Желаемое время начала')),
                ('desired_duration', models.DurationField(verbose_name='Желаемая длительность')),
                ('status', models.CharField(choices=[('waiting', 'В очереди'), ('notified', 'Оповещен'), ('booked', 'Забронировано'), ('expired', 'Истекло'), ('cancelled', 'Отменено')], default='waiting', max_length=20, verbose_name='Статус')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда оповещен')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия оповещения')),
            ],
            options={
                'verbose_name': 'Запись в листе ожидания',
                'verbose_name_plural': 'Листы ожидания',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Время окончания')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Факт заезда')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Факт выезда')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('participants_count', models.PositiveIntegerField(default=1, help_text='Для групповых броней bootcamp-зоны', verbose_name='Количество участников')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('club', models.ForeignKey(help_text='Денормализовано для быстрых выборок', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
