# Generated by Django 6.1.1 on 2026-10-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('logo', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkstationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='catalog.game')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='clubs.workstation')),
            ],
            options={
                'unique_together': {('workstation', 'game')},
            },
        ),
    ]
