version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pc_club_db
    environment:
      POSTGRES_DB: pc_club_db
      POSTGRES_USER: pc_club_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5342:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: pc_club_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
