# Generated by Django 6.1.1 on 2026-10-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Фиксирует цену товара, чтобы она не изменилась в истории при смене цены в меню', max_digits=10, verbose_name='Цена на момент заказа')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('cooking', 'Готовится'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость')),
                ('payment_method', models.CharField(choices=[('bonus', 'Бонусы'), ('cash', 'Наличные'), ('card', 'Карта')], max_length=20, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bookings.booking', verbose_name='Привязка к сессии (брони)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
