# Generated by Django 6.1.1 on 2026-09-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('adress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=50, unique=True)),
                ('longitude', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('photos', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('it_24h', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Например: Logitech, Razer', max_length=50)),
                ('model_name', models.CharField(help_text='Например: G Pro X Superlight', max_length=100)),
                ('device_type', models.CharField(choices=[('MOUSE', 'Мышь'), ('KEYBOARD', 'Клавиатура'), ('HEADSET', 'Гарнитура'), ('MONITOR', 'Монитор'), ('CHAIR', 'Кресло')], max_length=20)),
                ('specs', models.TextField(blank=True, help_text='Например: 25600 DPI, беспроводная', null=True)),
            ],
            options={
                'verbose_name': 'Девайсы',
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('monitor', models.CharField(max_length=255)),
                ('monitor_refresh_rate', models.CharField(max_length=255)),
                ('peripherals', models.ManyToManyField(blank=True, help_text='Выберите девайсы, установленные в этой зоне', related_name='zones', to='clubs.peripheral')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP Room'), ('BOOTCAMP', 'Bootcamp')], default='STANDART', max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Количество мест в зоне')),
                ('color', models.CharField(default='#FFFFFF', help_text='hex-код цвета', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Имя иконки для фронтенда', max_length=50, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zone', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ZonePriceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('WEEKDAYS', 'Будни (Пн-Пт)'), ('WEEKENDS', 'Выходные (Сб-Вс)')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_modifiers', to='clubs.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Workstaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_label', models.CharField(help_text='Например: PC-12, PS5-02', max_length=20)),
                ('device_type', models.CharField(choices=[('PC', 'ПК'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X/S')], default='PC', max_length=10)),
                ('status', models.CharField(choices=[('FREE', 'Свободно'), ('OCCUPIED', 'Занято'), ('RESERVED', 'Забронировано'), ('MAINTENANCE', 'Тех. обслуживание')], default='FREE', max_length=15)),
                ('position_x', models.IntegerField(blank=True, help_text='X-координата (в пикселях или процентах)', null=True)),
                ('position_y', models.IntegerField(blank=True, help_text='Y-координата (в пикселях или процентах)', null=True)),
                ('hardware_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations', to='clubs.hardwareprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='clubs.zone')),
            ],
            options={
                'verbose_name': 'Рабочие места',
                'unique_together': {('zone', 'number_label')},
            },
        ),
    ]
