# Generated by Django 6.1.1 on 2026-09-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('STANDART', 'Standart'), ('VIP', 'VIP Room'), ('BOOTCAMP', 'Bootcamp'), ('PS5', 'ps5')], default='STANDART', max_length=25),
        ),
    ]
