# Generated by Django 6.1.1 on 2026-10-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('banner', models.URLField(blank=True, max_length=255, null=True, verbose_name='Баннер')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed_amount', 'Fixed Amount'), ('bonus_multiplier', 'Bonus Multiplier'), ('free_hour', 'Free Hour')], max_length=25, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Размер скидки (процент, сумма в рублях или множитель бонусов)', max_digits=10)),
                ('promo_code', models.CharField(blank=True, help_text='Опциональный промокод для активации', max_length=50, null=True, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('applicable_zone', models.ForeignKey(blank=True, help_text='Оставьте пустым, если акция действует для всех зон', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='clubs.zone')),
                ('club', models.ForeignKey(blank=True, help_text='Оставьте пустым, если акция действует во всех клубах сети', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-start_date'],
            },
        ),
    ]
