# Generated by Django 6.1.1 on 2026-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tier', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], help_text='Опциональный уровень лояльности', max_length=15, null=True)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аккаунт лояльности',
                'verbose_name_plural': 'Аккаунты лояльности',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('booking', 'Booking'), ('order', 'Order')], help_text='Тип действия, за которое начисляются баллы', max_length=20, unique=True)),
                ('points_per_unit', models.DecimalField(decimal_places=4, help_text='Коэффициент начисления. Например, 0.1 означает 1 балл за каждые 10 ₽', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Правило лояльности',
                'verbose_name_plural': 'Правила лояльности',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма начисления (может быть отрицательной при списании)', max_digits=10)),
                ('type', models.CharField(choices=[('earn_booking', 'Earned from Booking'), ('earn_order', 'Earned from Order'), ('spend', 'Spent'), ('manual_admin', 'Manual Admin Entry'), ('referral', 'Referral Bonus')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция лояльности',
                'verbose_name_plural': 'Транзакции лояльности',
                'ordering': ['-created_at'],
            },
        ),
    ]
